
FIND_PATH(KINECTAPI_INCLUDE_DIR NuiApi.h
	PATH_SUFFIXES
		/inc/
	PATHS
		$ENV{KINECTAPI_DIR}
		$ENV{KINECTSDK10_DIR}
		"C:/Program Files/Microsoft SDKs/Kinect/v1.0/"
)

MACRO(FIND_KINECTAPI_LIBRARY MYLIBRARY MYLIBRARYNAME)

    FIND_LIBRARY(${MYLIBRARY}
        NAMES ${MYLIBRARYNAME}
		PATH_SUFFIXES
			/lib/
			/lib/x86/
			/lib/amd64/
        PATHS
			$ENV{KINECTAPI_DIR}
			$ENV{KINECTSDK10_DIR}
			"C:/Program Files/Microsoft SDKs/Kinect/v1.0/"
    )

ENDMACRO(FIND_KINECTAPI_LIBRARY LIBRARY LIBRARYNAME)

FIND_KINECTAPI_LIBRARY(KINECTAPI_LIBRARY Kinect10)

SET(KINECTAPI_FOUND "NO")
IF(FIND_KINECTAPI_LIBRARY AND KINECTAPI_INCLUDE_DIR)
    SET(KINECTAPI_FOUND "YES")
ENDIF(FIND_KINECTAPI_LIBRARY AND KINECTAPI_INCLUDE_DIR)
